name: first_experience
description: First Experience of Ficcious Team.


publish_to:


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  video_player: ^2.1.10
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true


  assets:
    - assets/images/